// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Login$WhatDidIEat = require("./Login.bs.js");

var initialState = /* record */[/* loginStatus : NotLoggedIn */0];

function reducer(_state, action) {
  if (action) {
    return /* record */[/* loginStatus : LoggedIn */[action[0]]];
  } else {
    return /* record */[/* loginStatus : NotLoggedIn */0];
  }
}

function App(Props) {
  var token = Props.token;
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  React.useEffect((function () {
          console.log("token: ", Js_option.getWithDefault("No token", token));
          return ;
        }), /* array */[token]);
  var match$1 = match[0][/* loginStatus */0];
  return React.createElement("div", undefined, match$1 ? React.createElement("div", undefined, "Logged in: " + match$1[0]) : React.createElement(Login$WhatDidIEat.make, {
                    onLoginSuccess: (function (token) {
                        return Curry._1(dispatch, /* Login */[token]);
                      })
                  }));
}

var make = App;

exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
