// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var App$WhatDidIEat = require("./App.bs.js");
var Aws$WhatDidIEat = require("./Aws.bs.js");
var AwsExports$WhatDidIEat = require("./AwsExports.bs.js");

var token = localStorage.getItem("token");

var token$1 = (token == null) ? undefined : Caml_option.some(token);

console.log("token", token$1);

Aws$WhatDidIEat.Amplify.configure(AwsExports$WhatDidIEat.identityPoolId, AwsExports$WhatDidIEat.region, AwsExports$WhatDidIEat.userPoolId, AwsExports$WhatDidIEat.userPoolWebClientId);

ReactDOMRe.renderToElementWithId(React.createElement(App$WhatDidIEat.make, {
          token: token$1
        }), "app");

exports.token = token$1;
/* token Not a pure module */
